### ISSUE TITLE
cann't clear article in test_plan page

### ISSUE THREAD

**Issue by ghada-37** [modeso-open-source/1lims-automation#136]
this line 
https://github.com/modeso-open-source/1lims-automation/blob/7843c4080101d13d13f10d97120004f0b4d9cc6f/ui_testing/testcases/basic_tests/test02_articles.py#L260
doesn't work due to this issue :

https://github.com/modeso-open-source/1lims-automation/blob/7843c4080101d13d13f10d97120004f0b4d9cc6f/ui_testing/pages/testplan_page.py#L13

this line gives this error message 
`TypeError: argument of type 'NoneType' is not iterable
`

I don't know why you need this if condition ?!

**Comment by 0xIslamTaha** [comment]
@ghada-37 
![image](https://user-images.githubusercontent.com/17981089/72056901-c69bb880-32cd-11ea-9a0e-3f9869d12d0d.png)

it is the clickable item in the article fields.
